# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7b40ba3350751a1fcd0721e14cdcd07dab12a01f16e97d5ecac6d6d36acb1f2078f242b3931d327874ced22109c23a36812a9acb625a1424fcaf82f81affd85

test:
  secret_key_base: 5225b8c5324ae1784b1a00773a03da6d65157a6cfea795fa8ed770c95b4c730b4f67dccd21084ae40613a848b45814a1990d38bc22b13571eb8d49237fb7096d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
